[package]
name = "servus"
version = "0.1.0"
authors = ["Auke Willem Oosterhoff <aukewillem.oosterhoff@mobilityhouse.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
